version: '3'

services:

  # references:
  # https://hub.docker.com/_/neo4j/
  # https://neo4j.com/docs/graph-data-science/current/installation/#installation
  # https://github.com/neo4j-contrib/neo4j-apoc-procedures
  neo4j:
    image: neo4j:4.2.4
    container_name: neo4j-server
    restart: always
    ports:
      # HTTP port
      - "7474:7474"
      # Bolt port
      - "7687:7687"
    environment: 
      NEO4J_AUTH: none
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\"]"


