version: '3'

services:

  # references:
  # https://hub.docker.com/_/neo4j/
  # https://neo4j.com/docs/graph-data-science/current/installation/#installation
  # https://github.com/neo4j-contrib/neo4j-apoc-procedures
  neo4j:
    image: neo4j:4.2.4
    container_name: neo4j-server
    restart: always
    ports:
      # HTTP port
      - "7474:7474"

      # Bolt port
      - "7687:7687"

    volumes:
      - ./storage/data:/data

    environment: 

      # No authentication needed
      NEO4J_AUTH: none

      # Optional libs to enable:
      # * apoc - APOC stands for Awesome Procedures on Cypher
      #   APOC allows developers to use a standard library for common procedures 
      #   and only write their own functionality for business logic and use-case-specific needs.
      # * graph-data-science - This library provides efficiently implemented, 
      #   parallel versions of common graph algorithms for Neo4j, exposed as Cypher procedures.
      NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\"]"

      # https://neo4j.com/labs/apoc/4.1/config/
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      


